### your site title here

title: Curie Kim
description: Computer Vision Researcher | Gwangju Institute of Science and Technology |

baseurl: /gradfolio #name of GitHub repository
url: "https://github.com/curie3170/curie3170.github.io.git/" #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
github: "https://github.com/curie3170"
google: "https://scholar.google.com/citations?user=DN1ps7wAAAAJ"
linkedin: "https://www.linkedin.com/in/curie-kim-219a78190/"
github: "https://github.com/curie3170"
#researchgate: "#"

#orcid: ""


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - 1.md
      - 2.md
      - 3.md
      - 4.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
